### ISSUE TITLE
File missing for running example comparison

### ISSUE THREAD

**Issue by gapartel** [EngreitzLab/CRISPR_comparison#3]
Hi, thank you for this nice resource!

I was trying to run the example comparison workflow

`nakemake --use-conda results/example/example_crispr_comparison.html -j1 -n`

 but a file seem to be missing the repo:

`Missing input files for rule mergePredictionsWithExperiment:
    output: results/example/expt_pred_merged.txt.gz
    wildcards: comparison=example
    affected files:
        resources/genomic_features/K562_expressed_genes.tsv
`

**Comment by NicoleYY77** [comment]
I didn't find the file results/example/example_crispr_comparison.html , either.... have you found the solution?

**Comment by 613weilin** [comment]
> I didn't find the file results/example/example_crispr_comparison.html , either.... have you found the solution?

`results/example/example_crispr_comparison.html` is the final output file, it will be generated when you run the pipeline.

**Comment by NicoleYY77** [comment]
> > I didn't find the file results/example/example_crispr_comparison.html , either.... have you found the solution?
> 
> `results/example/example_crispr_comparison.html` is the final output file, it will be generated when you run the pipeline.

Thanks for telling! I just found that, too
